/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScorersRouteImport } from './routes/scorers'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as MatchFixtureIdRouteImport } from './routes/match.$fixtureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorersRoute = ScorersRouteImport.update({
  id: '/scorers',
  path: '/scorers',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MatchFixtureIdRoute = MatchFixtureIdRouteImport.update({
  id: '/match/$fixtureId',
  path: '/match/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fixtures': typeof FixturesRoute
  '/results': typeof ResultsRoute
  '/scorers': typeof ScorersRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/match/$fixtureId': typeof MatchFixtureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fixtures': typeof FixturesRoute
  '/results': typeof ResultsRoute
  '/scorers': typeof ScorersRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/match/$fixtureId': typeof MatchFixtureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/fixtures': typeof FixturesRoute
  '/results': typeof ResultsRoute
  '/scorers': typeof ScorersRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/match/$fixtureId': typeof MatchFixtureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fixtures'
    | '/results'
    | '/scorers'
    | '/standings'
    | '/teams'
    | '/admin'
    | '/match/$fixtureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fixtures'
    | '/results'
    | '/scorers'
    | '/standings'
    | '/teams'
    | '/admin'
    | '/match/$fixtureId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/fixtures'
    | '/results'
    | '/scorers'
    | '/standings'
    | '/teams'
    | '/_authenticated/admin'
    | '/match/$fixtureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FixturesRoute: typeof FixturesRoute
  ResultsRoute: typeof ResultsRoute
  ScorersRoute: typeof ScorersRoute
  StandingsRoute: typeof StandingsRoute
  TeamsRoute: typeof TeamsRoute
  MatchFixtureIdRoute: typeof MatchFixtureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorers': {
      id: '/scorers'
      path: '/scorers'
      fullPath: '/scorers'
      preLoaderRoute: typeof ScorersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/match/$fixtureId': {
      id: '/match/$fixtureId'
      path: '/match/$fixtureId'
      fullPath: '/match/$fixtureId'
      preLoaderRoute: typeof MatchFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FixturesRoute: FixturesRoute,
  ResultsRoute: ResultsRoute,
  ScorersRoute: ScorersRoute,
  StandingsRoute: StandingsRoute,
  TeamsRoute: TeamsRoute,
  MatchFixtureIdRoute: MatchFixtureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
